/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class u_can_i_up_app_MainActivity */

#ifndef _Included_u_can_i_up_app_MainActivity
#define _Included_u_can_i_up_app_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
JNIEXPORT jint JNICALL Java_u_can_i_up_app_MainActivity_testInt(JNIEnv* env, jobject obj);
JNIEXPORT jstring JNICALL Java_u_can_i_up_app_MainActivity_testString(JNIEnv* env, jobject obj);
JNIEXPORT jstring JNICALL Java_u_can_i_up_app_MainActivity_sendSMS(JNIEnv* env, jobject thiz);
JNIEXPORT jstring JNICALL Java_u_can_i_up_app_MainActivity_getLocation(JNIEnv* env, jobject thiz);
}
#endif
#endif
